# Generated by Django 5.0.6 on 2025-04-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotification',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
    ]
