# Generated by Django 5.0.6 on 2025-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contact_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('stars', models.CharField(max_length=5)),
                ('Content', models.CharField(max_length=255)),
            ],
        ),
    ]
