# Generated by Django 5.0.6 on 2025-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ourteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.FileField(blank=True, default='team_images/Logo_IntelliSurge_TM_No_BG.png', null=True, upload_to='team_images/'),
        ),
    ]
