# Generated by Django 5.0.6 on 2025-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_blog_image_url_blog_image_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, default='team_images/Logo_IntelliSurge_TM_No_BG.png', null=True, upload_to='Blog_image/'),
        ),
    ]
