# Generated by Django 5.0.6 on 2025-04-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ourteamcareer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteamcareer',
            name='Content',
        ),
    ]
