# Generated by Django 5.0.6 on 2025-04-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
