# Generated by Django 5.0.6 on 2025-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_event_leadershipmember_ministryitem_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='leadershipmember',
            name='image',
            field=models.ImageField(upload_to='leadership_images/'),
        ),
        migrations.AlterField(
            model_name='ministryitem',
            name='image',
            field=models.ImageField(upload_to='ministry_images/'),
        ),
    ]
