# Generated by Django 5.0.6 on 2025-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_booking_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
