# Generated by Django 5.0.6 on 2025-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_name',
            field=models.CharField(default='item1', max_length=255),
        ),
    ]
