# Generated by Django 5.0.6 on 2025-05-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_payment_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
