# Generated by Django 5.0.6 on 2025-04-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobnotification_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnotification',
            name='job_title',
        ),
    ]
