# Generated by Django 5.0.6 on 2025-04-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnotification',
            name='apply_link',
        ),
    ]
