# Generated by Django 5.0.6 on 2025-04-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobnotification_apply_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
