# Generated by Django 5.0.6 on 2025-04-14 06:43

from django.db import migrations, models

def add_default_admin(apps, schema_editor):
    AdminUser = apps.get_model('core', 'AdminUser')
    if not AdminUser.objects.filter(email='admin@admin.com').exists():
        AdminUser.objects.create(email='admin@admin.com', password='admin123')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jobapplication_resume_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
