# Generated by Django 5.0.6 on 2025-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_adminuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('technologies', models.TextField(verbose_name='Technologies Client is Looking For')),
                ('message', models.TextField()),
            ],
        ),
    ]
