# Generated by Django 5.0.6 on 2025-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='technologies',
            field=models.TextField(),
        ),
    ]
