# Generated by Django 5.0.6 on 2025-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ourteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.FileField(default='team_images/Logo_IntelliSurge_TM_No_BG.png', upload_to='team_images/'),
        ),
    ]
