# Generated by Django 5.0.6 on 2025-04-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.FileField(default='team_images/Logo_IntelliSurge_TM_No_BG.png', upload_to='team_images/')),
                ('Content', models.CharField(max_length=255)),
            ],
        ),
    ]
