# Generated by Django 5.0.6 on 2025-05-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
