# Generated by Django 5.0.6 on 2025-05-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_ticket_paid_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paid',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('false', 'Not Paid')], default='false', max_length=20),
        ),
    ]
